# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


### Mine ###
wake_on_lan:
switch:
    - platform: wake_on_lan
      mac: 2C-F0-5D-86-27-F5
      name: Desktop PC

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.87.150:3218/
    require_admin: true
